[general]
import = [
    "~/.config/alacritty/themes/tokyonight_night.toml"
]

[env]
TERM = "xterm-256color"
# TERM = "alacritty"
# WINIT_X11_SCALE_FACTOR = "1.0"

[window]
position.x = 3500
position.y = 1000
dimensions.columns = 160
dimensions.lines = 48
padding.x = 10
padding.y = 10
decorations = "Buttonless"
# opacity = 0.75
# blur = true 

[font]
normal.family = "DepartureMono Nerd Font Mono"
size = 15.0
