[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
position.x = 3500
position.y = 1000
dimensions.columns = 200
dimensions.lines = 50
padding.x = 8
padding.y = 8
decorations = "Buttonless"
opacity = 0.75
blur = true 

[font]
size = 14.0
[font.normal]
family = "Iosevka Nerd Font Mono"
style = "Regular"
[font.italic]
family = "Iosevka Nerd Font Mono"
style = "Italic"
[font.bold]
family = "Iosevka Nerd Font Mono"
style = "Bold"
[font.bold_italic]
family = "Iosevka Nerd Font Mono"
style = "Bold Italic"
