#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar, these are only some of the
# options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

# display can be main/all/integer

sketchybar --bar height=40        \
                 blur_radius=0   \
                 position=bottom  \
                 sticky=off       \
                 padding_left=0   \
                 padding_right=0  \
                 margin=2         \
                 y_offset=4       \
                 shadow=off       \
                 display=main     \
                 color=$BAR_COLOR

##### Changing Defaults #####
# We now change some default values that are applied to all further items
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

sketchybar --default icon.font="SF Pro:Semibold:14.0"      \
                     icon.color=$WHITE                     \
                     label.font="SF Pro:Semibold:14.0"     \
                     label.color=$WHITE                    \
                     background.color=$ITEM_BG_COLOR       \
                     background.corner_radius=6            \
                     background.height=24                  \
                     padding_left=5                        \
                     padding_right=5                       \
                     label.padding_left=4                  \
                     label.padding_right=10                \
                     icon.padding_left=10                  \
                     icon.padding_right=4

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
# source $ITEM_DIR/media.sh

# -- Right Side Items --
# source $ITEM_DIR/calendar.sh
# source $ITEM_DIR/volume.sh
# source $ITEM_DIR/battery.sh
# source $ITEM_DIR/cpu.sh


##### Finalizing Setup #####
sketchybar --hotload on
# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update
