fork = true # default: false
idle = true
maximized = false
tabs = true
vsync = true

srgb = true
frame = "buttonless" # full, none, transparent, buttonless
title-hidden = true
mouse-cursor-icon = "arrow"

[font]
normal = ["IBM Plex Mono"] # Will use the bundled Fira Code Nerd Font by default
size = 16.0
hinting = "full"
edging = "antialias"
