[colors]
ansi = [
  "#27272a",
  "#ea83a5",
  "#90b99f",
  "#e6b99d",
  "#9ca2cf",
  "#e29eca",
  "#85b6ba",
  "#c9c7cd"
]
brights = [
  "#353539",
  "#ed96b3",
  "#a7c8b3",
  "#eac5ae",
  "#acb1d7",
  "#e8b0d4",
  "#97c0c4",
  "#c9c7cd"
]
cursor_bg = "#c9c7cd" 
cursor_border = "#c9c7cd" 
cursor_fg = "#161617" 
background = "#161617"
foreground = "#c9c7cd" 
selection_bg = "#3c3b3e" 
selection_fg = "#c9c7cd"  

[metadata]
name = "oldworld"
author = "dgox16"
origin_url = "https://github.com/dgox16/oldworld.nvim"

